CREATE DATABASE IF NOT EXISTS expense_tracker;
USE expense_tracker;

CREATE TABLE IF NOT EXISTS users (
    USER_ID VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    otp_code VARCHAR(10),
    otp_expires_at DATETIME,
    reset_otp_code VARCHAR(10),
    reset_otp_expires_at DATETIME,
    is_verified BOOLEAN DEFAULT FALSE,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
    Expense_ID VARCHAR(255) PRIMARY KEY,
    User_ID VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    Category VARCHAR(100) NOT NULL,
    Date_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES users(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_income (
    User_ID VARCHAR(255) PRIMARY KEY,
    Monthly_Income DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES users(USER_ID) ON DELETE CASCADE
);
